version = 0.1
[account_esc.deploy.parameters]
stack_name = "Efrei-Sport-Climbing-App"
resolve_s3 = true
s3_prefix = "Efrei-Sport-Climbing-App"
region = "eu-west-3"
profile = "account_esc"
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []

[default.deploy.parameters]
stack_name = "EfreiSportClimbingTest"
s3_bucket = "efrei-sam-artifacts-bucket"
resolve_s3 = false
s3_prefix = "EfreiSportClimbingTest"
region = "eu-west-3"
profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
