import {
    DiscordActionRow,
    DiscordButton,
    DiscordEmbed,
    DiscordMessagePost,
} from '../../../layers/commons/discord.types';

export async function sendDiscordAlert(
    message: string,
    channelId: string,
    token: string,
    buttons: DiscordButton[] | null = null,
): Promise<void> {
    const url = `https://discord.com/api/v8/channels/${channelId}/messages`;

    const embed: DiscordEmbed = {
        title: 'HelloAsso Event Alert',
        description: message,
        color: 0xff0000, // Red color for alerts
        footer: {
            text: 'Generated by HelloAsso Event Handler',
        },
    };

    const body: DiscordMessagePost = {
        embeds: [embed],
    };

    if (buttons && buttons.length > 0) {
        const actionRow: DiscordActionRow = {
            type: 1, // ActionRow type
            components: buttons,
        };
        body.components = [actionRow];
    }

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bot ${token}`,
        },
        body: JSON.stringify(body),
    });

    if (!response.ok) {
        console.log(`Failed to send Discord alert: ${await response.json().then((data) => data.message)}`);
        throw new Error(`Failed to send Discord alert: ${response.statusText}`);
    }
}
